// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $contacto from "./routes/contacto.tsx";
import * as $corporaciones from "./routes/corporaciones.tsx";
import * as $galeria from "./routes/galeria.tsx";
import * as $index from "./routes/index.tsx";
import * as $notijimbo from "./routes/notijimbo.tsx";
import * as $perfiles from "./routes/perfiles.tsx";
import * as $testimonios from "./routes/testimonios.tsx";
import * as $tv_jimbo from "./routes/tv-jimbo.tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/contacto.tsx": $contacto,
    "./routes/corporaciones.tsx": $corporaciones,
    "./routes/galeria.tsx": $galeria,
    "./routes/index.tsx": $index,
    "./routes/notijimbo.tsx": $notijimbo,
    "./routes/perfiles.tsx": $perfiles,
    "./routes/testimonios.tsx": $testimonios,
    "./routes/tv-jimbo.tsx": $tv_jimbo,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
