// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $acuafitting from "./routes/acuafitting.tsx";
import * as $admin_middleware from "./routes/admin/_middleware.ts";
import * as $admin_customers from "./routes/admin/customers.tsx";
import * as $admin_dashboard from "./routes/admin/dashboard.tsx";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $admin_leads from "./routes/admin/leads.tsx";
import * as $admin_logout from "./routes/admin/logout.tsx";
import * as $admin_products from "./routes/admin/products.tsx";
import * as $admin_products_edit_id_ from "./routes/admin/products/edit/[id].tsx";
import * as $admin_products_new from "./routes/admin/products/new.tsx";
import * as $api_middleware from "./routes/api/_middleware.ts";
import * as $api_auth_login from "./routes/api/auth/login.ts";
import * as $api_auth_me from "./routes/api/auth/me.ts";
import * as $api_customers_id_ from "./routes/api/customers/[id].ts";
import * as $api_customers_index from "./routes/api/customers/index.ts";
import * as $api_leads_id_ from "./routes/api/leads/[id].ts";
import * as $api_leads_convert from "./routes/api/leads/convert.ts";
import * as $api_leads_index from "./routes/api/leads/index.ts";
import * as $index from "./routes/index.tsx";
import * as $soluciones_en_agua from "./routes/soluciones-en-agua.tsx";
import * as $wattersolutions from "./routes/wattersolutions.tsx";
import * as $DeleteConfirmation from "./islands/DeleteConfirmation.tsx";
import * as $ProductForm from "./islands/ProductForm.tsx";
import * as $SearchForm from "./islands/SearchForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/acuafitting.tsx": $acuafitting,
    "./routes/admin/_middleware.ts": $admin_middleware,
    "./routes/admin/customers.tsx": $admin_customers,
    "./routes/admin/dashboard.tsx": $admin_dashboard,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/admin/leads.tsx": $admin_leads,
    "./routes/admin/logout.tsx": $admin_logout,
    "./routes/admin/products.tsx": $admin_products,
    "./routes/admin/products/edit/[id].tsx": $admin_products_edit_id_,
    "./routes/admin/products/new.tsx": $admin_products_new,
    "./routes/api/_middleware.ts": $api_middleware,
    "./routes/api/auth/login.ts": $api_auth_login,
    "./routes/api/auth/me.ts": $api_auth_me,
    "./routes/api/customers/[id].ts": $api_customers_id_,
    "./routes/api/customers/index.ts": $api_customers_index,
    "./routes/api/leads/[id].ts": $api_leads_id_,
    "./routes/api/leads/convert.ts": $api_leads_convert,
    "./routes/api/leads/index.ts": $api_leads_index,
    "./routes/index.tsx": $index,
    "./routes/soluciones-en-agua.tsx": $soluciones_en_agua,
    "./routes/wattersolutions.tsx": $wattersolutions,
  },
  islands: {
    "./islands/DeleteConfirmation.tsx": $DeleteConfirmation,
    "./islands/ProductForm.tsx": $ProductForm,
    "./islands/SearchForm.tsx": $SearchForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
