// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin_cms from "./routes/admin/cms.tsx";
import * as $admin_content_delete_id_ from "./routes/admin/content/delete/[id].tsx";
import * as $admin_content_edit_id_ from "./routes/admin/content/edit/[id].tsx";
import * as $admin_content_index from "./routes/admin/content/index.tsx";
import * as $admin_content_new from "./routes/admin/content/new.tsx";
import * as $admin_crm from "./routes/admin/crm.tsx";
import * as $admin_crm_contacts_delete_id_ from "./routes/admin/crm/contacts/delete/[id].tsx";
import * as $admin_crm_contacts_edit_id_ from "./routes/admin/crm/contacts/edit/[id].tsx";
import * as $admin_crm_contacts_index from "./routes/admin/crm/contacts/index.tsx";
import * as $admin_crm_contacts_new from "./routes/admin/crm/contacts/new.tsx";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $admin_login from "./routes/admin/login.tsx";
import * as $admin_logout from "./routes/admin/logout.tsx";
import * as $index from "./routes/index.tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin/cms.tsx": $admin_cms,
    "./routes/admin/content/delete/[id].tsx": $admin_content_delete_id_,
    "./routes/admin/content/edit/[id].tsx": $admin_content_edit_id_,
    "./routes/admin/content/index.tsx": $admin_content_index,
    "./routes/admin/content/new.tsx": $admin_content_new,
    "./routes/admin/crm.tsx": $admin_crm,
    "./routes/admin/crm/contacts/delete/[id].tsx":
      $admin_crm_contacts_delete_id_,
    "./routes/admin/crm/contacts/edit/[id].tsx": $admin_crm_contacts_edit_id_,
    "./routes/admin/crm/contacts/index.tsx": $admin_crm_contacts_index,
    "./routes/admin/crm/contacts/new.tsx": $admin_crm_contacts_new,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/admin/login.tsx": $admin_login,
    "./routes/admin/logout.tsx": $admin_logout,
    "./routes/index.tsx": $index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
